In [170]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
%matplotlib inline

import warnings
warnings.filterwarnings('ignore')

In [10]:
import numpy as np

def batch_gradient_descent(X, y_true, epochs, learning_rate):
    number_of_features = X.shape[1]
    W = np.ones(shape=(number_of_features))
    b = 0
    cost_list = []
    epoch_list = []

    for i in range(epochs):
        y_predicted = np.dot(X, W) + b

        w_grad = -(2/len(X)) * np.dot(X.T, (y_true - y_predicted))
        b_grad = -(2/len(X)) * np.sum(y_true - y_predicted)

        W = W - learning_rate * w_grad
        b -= learning_rate * b_grad

        cost = np.mean(np.square(y_true - y_predicted))

        if i % 100 == 0:
            cost_list.append(cost)
            epoch_list.append(i)

    return W, b, cost, cost_list, epoch_list

In [119]:
import random


def stochastic_gradient_descent(X, y_true, epochs, learning_rate):
    number_of_features = X.shape[1]
    W = np.ones(shape=(number_of_features))
    b = 0
    cost_list = []
    epoch_list = []
    
    for i in range(epochs):
        random_index = random.randint(0,X.shape[0]-1)
        X_sample = X[random_index]
        y_sample = y_true[random_index]
    
        y_predicted = np.dot(X_sample,W) + b

        w_grad = -(2/X.shape[0]) * np.dot(X_sample.T, (y_sample - y_predicted))
        b_grad = -(2/X.shape[0]) * np.sum(y_sample - y_predicted)

        W = W - learning_rate * w_grad
        b -= learning_rate * b_grad

        cost = np.mean(np.square(y_sample - y_predicted))

        if i % 100 == 0:
            cost_list.append(cost)
            epoch_list.append(i)

    return W, b, cost, cost_list, epoch_list


""" 
def stochastic_gradient_descent(X, y, epochs, learning_rate):
    number_of_features = X.shape[1]
    W = np.ones(shape=(number_of_features))
    b = 0
    cost_list = []
    epoch_list = []

    total_samples = len(X)

    for epoch in range(epochs):
        cost_epoch = 0
        for i in range(total_samples):
            random_index = np.random.randint(total_samples)
            X_i = X[random_index]
            y_i = y[random_index]

            y_predicted = np.dot(X_i, W) + b

            w_grad = -(2 / total_samples) * X_i * (y_i - y_predicted)
            b_grad = -(2 / total_samples) * (y_i - y_predicted)

            W -= learning_rate * w_grad
            b -= learning_rate * b_grad

            cost = np.square(y_i - y_predicted)
            cost_epoch += cost

        cost_list.append(cost_epoch / total_samples)
        epoch_list.append(epoch)

    return W, b, cost_list, epoch_list


"""

In [121]:
import random

def mini_gradient_descent(X, y_true, epochs, learning_rate):
    number_of_features = X.shape[1]
    W = np.ones(shape=(number_of_features))
    b = 0
    cost_list = []
    epoch_list = []
    
    for i in range(epochs):
        random_index_i = random.randint(0,X.shape[0]-1)
        random_index_j = random.randint(random_index_i,X.shape[0]-1)
        
        X_sample = X[random_index_i:random_index_j]
        y_sample = y_true[random_index_i:random_index_j]
    
        y_predicted = np.dot(X_sample,W) + b

        w_grad = -(2/X.shape[0]) * np.dot(X_sample.T, (y_sample - y_predicted))
        b_grad = -(2/X.shape[0]) * np.sum(y_sample - y_predicted)

        W = W - learning_rate * w_grad
        b -= learning_rate * b_grad

        cost = np.mean(np.square(y_sample - y_predicted))

        if i % 100 == 0:
            cost_list.append(cost)
            epoch_list.append(i)

    return W, b, cost, cost_list, epoch_list

In [13]:
df = pd.read_csv("homeprices_banglore.csv")
df.sample(5)

area  bedrooms   price
12  1000         2   38.00
6   2732         4  135.00
4   1200         2   51.00
0   1056         2   39.07
10  1800         3   82.00

In [33]:
from sklearn import preprocessing
sx = preprocessing.MinMaxScaler()
sy = preprocessing.MinMaxScaler()

scaled_X = sx.fit_transform(df.drop('price',axis='columns'))
scaled_y = sy.fit_transform(df['price'].values.reshape(df.shape[0],1))

scaled_X

array([[0.08827586, 0.25      ],
       [0.62068966, 0.75      ],
       [0.22068966, 0.5       ],
       [0.24862069, 0.5       ],
       [0.13793103, 0.25      ],
       [0.12758621, 0.25      ],
       [0.6662069 , 0.75      ],
       [0.86206897, 0.75      ],
       [0.17586207, 0.5       ],
       [1.        , 1.        ],
       [0.34482759, 0.5       ],
       [0.68448276, 0.75      ],
       [0.06896552, 0.25      ],
       [0.10344828, 0.25      ],
       [0.5       , 0.5       ],
       [0.12931034, 0.25      ],
       [0.13103448, 0.5       ],
       [0.25517241, 0.5       ],
       [0.67931034, 0.5       ],
       [0.        , 0.        ]])

In [34]:
scaled_y

array([[0.05237037],
       [0.65185185],
       [0.22222222],
       [0.31851852],
       [0.14074074],
       [0.04444444],
       [0.76296296],
       [0.91111111],
       [0.13333333],
       [1.        ],
       [0.37037037],
       [0.8       ],
       [0.04444444],
       [0.05925926],
       [0.51111111],
       [0.07407407],
       [0.11851852],
       [0.20740741],
       [0.51851852],
       [0.        ]])

In [31]:
scaled_y.reshape(scaled_y.shape[0],)

array([0.05237037, 0.65185185, 0.22222222, 0.31851852, 0.14074074,
       0.04444444, 0.76296296, 0.91111111, 0.13333333, 1.        ,
       0.37037037, 0.8       , 0.04444444, 0.05925926, 0.51111111,
       0.07407407, 0.11851852, 0.20740741, 0.51851852, 0.        ])

In [105]:
w, b, cost, cost_list, epoch_list = batch_gradient_descent(scaled_X,scaled_y.reshape(scaled_y.shape[0],),500,0.01)
w, b, cost

(array([0.70712464, 0.67456527]), -0.23034857438407427, 0.0068641890429808105)

In [120]:
w, b, cost, cost_list, epoch_list = stochastic_gradient_descent(scaled_X,scaled_y.reshape(scaled_y.shape[0],),10000,0.01)
w, b, cost

(array([0.70865319, 0.67799845]), -0.230178256854771, 0.005158228906995724)

In [126]:
w, b, cost, cost_list, epoch_list = mini_gradient_descent(scaled_X,scaled_y.reshape(scaled_y.shape[0],),10000,0.01)
w, b, cost

(array([0.69181179, 0.57366427]), -0.1734721636218009, 0.006821515363662935)

In [134]:
import numpy as np

def minii_gradient_descent(X, y, epochs, learning_rate, batch_size):
    number_of_features = X.shape[1]
    W = np.ones(shape=(number_of_features))
    b = 0
    cost_list = []
    epoch_list = []

    total_samples = len(X)

    for epoch in range(epochs):
        cost_epoch = 0
        indices = np.random.permutation(total_samples)
        X_shuffled = X[indices]
        y_shuffled = y[indices]

        for i in range(0, total_samples, batch_size):
            X_batch = X_shuffled[i:i+batch_size]
            y_batch = y_shuffled[i:i+batch_size]

            y_predicted = np.dot(X_batch, W) + b

            w_grad = -(2 / len(X_batch)) * np.dot(X_batch.T, (y_batch - y_predicted))
            b_grad = -(2 / len(X_batch)) * np.sum(y_batch - y_predicted)

            W -= learning_rate * w_grad
            b -= learning_rate * b_grad

            cost = np.mean(np.square(y_batch - y_predicted))
            cost_epoch += cost

        cost_list.append(cost_epoch / (total_samples // batch_size))
        epoch_list.append(epoch)

    return W, b,cost/ (total_samples // batch_size), cost_list, epoch_list

w, b, cost, cost_list, epoch_list = minii_gradient_descent(scaled_X,scaled_y.reshape(scaled_y.shape[0],),10000,0.01,3)
w, b, cost

(array([0.92216464, 0.20240508]), -0.07446888489097499, 0.0005363655677814361)

In [168]:
def predict(X,w,b):
    X= sx.transform(X)[0]
    y_predicted = np.dot(X, w) + b

    y_predicted = sy.inverse_transform([[y_predicted]])
    print(y_predicted)
    


In [171]:
predict([[1056,2]],w,b)

[[39.76753063]]
