In [19]:
import pandas as pd
import numpy as np
from tensorflow import unique
from tensorflow.keras import Sequential
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.layers import Dense,Flatten
from tensorflow.keras.datasets import mnist
from tensorflow.config import experimental
from tensorflow import device

In [2]:
(X_train,y_train),(X_test,y_test) = mnist.load_data()

In [3]:
len(X_train),len(X_test)

(60000, 10000)

In [4]:
X_train.shape

(60000, 28, 28)

In [5]:
X_train[0]

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   3,
         18,  18,  18, 126, 136, 175,  26, 166, 255, 247, 127,   0,   0,
          0,   0],
       [  

In [6]:
X_train_scaled = X_train/255
X_test_scaled = X_test/255

In [7]:
unique(y_train)

Unique(y=<tf.Tensor: shape=(10,), dtype=uint8, numpy=array([5, 0, 4, 1, 9, 2, 3, 6, 7, 8], dtype=uint8)>, idx=<tf.Tensor: shape=(60000,), dtype=int32, numpy=array([0, 1, 2, ..., 0, 7, 9])>)

In [8]:
y_train_categorical = to_categorical(y_train,num_classes=10,dtype='uint8')
y_test_categorical = to_categorical(y_test,num_classes=10,dtype='uint8')

In [13]:
def get_model(hidden_layer=1):
    layers = [Flatten(input_shape=(28, 28))]
    
    for i in range(hidden_layer):
        layers.append(Dense(3000,activation='relu'))
    layers.append(Dense(10, activation='sigmoid'))
    
    model = Sequential(layers)
    model.compile(optimizer='SGD',loss='categorical_crossentropy',metrics=['accuracy'])
    
    return model

In [14]:
model_one_hidden_layer = get_model()
model_one_hidden_layer.fit(X_train_scaled,y_train_categorical,epochs=5)

Epoch 1/5
1875/1875 [==============================] - 6s 3ms/step - loss: 0.5696 - accuracy: 0.8670
Epoch 2/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.3079 - accuracy: 0.9155
Epoch 3/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.2612 - accuracy: 0.9267
Epoch 4/5
1875/1875 [==============================] - 6s 3ms/step - loss: 0.2315 - accuracy: 0.9363
Epoch 5/5
1875/1875 [==============================] - 6s 3ms/step - loss: 0.2088 - accuracy: 0.9426


In [17]:
experimental.list_physical_devices() 

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [26]:
%%timeit -n1 -r1
with device('/GPU:0'):
    model = get_model(1)
    model.fit(X_train_scaled, y_train_categorical, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 7s 3ms/step - loss: 0.5686 - accuracy: 0.8657
Epoch 2/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.3089 - accuracy: 0.9143
Epoch 3/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.2626 - accuracy: 0.9275
Epoch 4/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.2330 - accuracy: 0.9354
Epoch 5/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.2101 - accuracy: 0.9420
27.6 s ± 0 ns per loop (mean ± std. dev. of 1 run, 1 loop each)


In [27]:
%%timeit -n1 -r1
with device('/GPU:0'):
    model = get_model(5)
    model.fit(X_train_scaled, y_train_categorical, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 23s 12ms/step - loss: 0.5237 - accuracy: 0.8615
Epoch 2/5
1875/1875 [==============================] - 22s 12ms/step - loss: 0.1874 - accuracy: 0.9463
Epoch 3/5
1875/1875 [==============================] - 22s 12ms/step - loss: 0.1308 - accuracy: 0.9612
Epoch 4/5
1875/1875 [==============================] - 22s 12ms/step - loss: 0.0989 - accuracy: 0.9710
Epoch 5/5
1875/1875 [==============================] - 22s 12ms/step - loss: 0.0761 - accuracy: 0.9776
1min 52s ± 0 ns per loop (mean ± std. dev. of 1 run, 1 loop each)


In [23]:
%%timeit -n1 -r1
with device('/CPU:0'):
    model = get_model(1)
    model.fit(X_train_scaled, y_train_categorical, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 22s 12ms/step - loss: 0.5658 - accuracy: 0.8686
Epoch 2/5
1875/1875 [==============================] - 21s 11ms/step - loss: 0.3079 - accuracy: 0.9158
Epoch 3/5
1875/1875 [==============================] - 21s 11ms/step - loss: 0.2620 - accuracy: 0.9269
Epoch 4/5
1875/1875 [==============================] - 21s 11ms/step - loss: 0.2322 - accuracy: 0.9357
Epoch 5/5
1875/1875 [==============================] - 21s 11ms/step - loss: 0.2094 - accuracy: 0.9423
1min 46s ± 0 ns per loop (mean ± std. dev. of 1 run, 1 loop each)
